from .constant_address import POLYGON_ADDR,FANTOM_ADDR
from .url_constants import (
    DIA_POLYGON_URL,DIA_FANTOM_URL,COINMARKETCAP_MIMATIC_URL,
    COINGECO_POLYGON_URL,COINGECKO_FANTOM_URL,SLACK_URL,GRAPHQL_URL
)