from .email_notification import send_email,generate_price_html_report,generate_breach_html_report
from .price_comparator import price_variation, price_threshold_breached
from .slack_integration import send_slack_notification
