name: mimatic monitoring and alerting job

on:
  schedule:
    - cron: '50 23 * * *'  # Runs at 23:50 GMT

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Environment Variables
        run: |
          echo "SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assuming your requirements are in this file

      - name: Run script
        run: python main.py
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
